name: RacesRewrite
version: '1.0-SNAPSHOT'
main: net.steppedtax.racesrewrite.RacesRewrite
api-version: '1.21.4'
commands:
  race:
    description: Debug command to change races.
    usage: "Usage: /<command> [undead|plant|blaze]"