name: RacesRewrite
version: '0.5.0'
main: net.steppedtax.racesrewrite.RacesRewrite
api-version: '1.21.5'
commands:
  race:
    description: Debug command to change races.
    usage: "Usage: /race [player] [undead | plant | blaze]"
  startupmsg:
    description: Debug command for config testing, changes the message displayed in server console on startup.
    usage: "Usage: /startupmsg [message]"